#ifndef SETTING_NAMES_H
#define SETTING_NAMES_H

#define STG_CRT_PATH    "GUI/CRT_PATH"
#define STG_TV_STATE    "GUI/MW/TV/STATE"
#define STG_TV_FILTER    "GUI/MW/TV/FILTER"

#define STG_MW_STATE    "GUI/MW/STATE"
#define STG_MW_GEOMETRY "GUI/MW/GEOMETRY"

#define STG_APPS_CMAKE  "APPS/CMAKE/EXE"
#define STG_APPS_GIT    "APPS/GIT/EXE"

#define STG_TEMPLATE_PATH       "TEMPLATE/PATH"

#define STG_OUTPUT_PATH         "OUTPUT/PATH"

#define STG_BACKUP_PATH         "BACKUP/PATH"

#define STG_CUSTOM_COMMANDS     "CUST_CMNDS"
#define STG_CUSTOM_CM_PROG      "PROGRAM"
#define STG_CUSTOM_CM_ARGS      "ARGUMENTS"
#define STG_CUSTOM_CM_CRTDIR    "DIR"
#define STG_CUSTOM_CM_NAME      "NAME"

#define STG_PILE_ARRAY          "piles/providers"

#define STG_NAV_MAX      "navigate/max"

#define STG_FAVOURITES_PATHS    "FAVOURITES/PATHS"


#define STG_SNIPP_DB        "SNIPPETS/DATABASE"
#define STG_ENVAR_DB        "ENV_VAR/DATABASE"


#endif // SETTING_NAMES_H
